#!/usr/bin/ruby

# Solution to https://projecteuler.net/problem=2
# Trey Thomas
#  
# | Each new term in the Fibonacci sequence is generated by adding the previous 
# | two terms. By starting with 1 and 2, the first 10 terms will be:
# | 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# | 
# | By considering the terms in the Fibonacci sequence whose values do not 
# | exceed four million, find the sum of the even-valued terms.
#
# 
#

class FibonacciSequence  
  def initialize
    @a = 1
    @b = 2
  end

  def next
    term = @a
    @a = @b
    @b += term
    return term
  end
end


sequence = FibonacciSequence.new
sum = 0

until (term = sequence.next) > 4_000_000
  if term.even?
    sum += term
  end
end

puts sum

